### ISSUE TITLE
Error when more than 4 publications listed for a person

### ISSUE THREAD

**Issue by eblerjana** [marschall-lab/marschall-lab.github.io#1]
I think I there is a bug on the current group website. If a person has more than 4 publications, this button "[see all XX publications with XX]" appears on their profile, however, if you click on that, an error message appears. This happens for Tobias' profile for example (he's the only one currently with > 4 papers): https://marschall-lab.github.io/people/tmarschall/. The error message is: ERROR `/person-publications/tmarschall' not found

**Comment by qwx9** [comment]
The problem is that for more than a (configurable) limit of papers, there's a separate page with its own layout, which must contain another file for each person like those in the _people/ subdirectory. It needs the same stuff, so one can either add a new one for some reason, or symlink their older one. I think that that's silly, so I propose to get rid of the limit and subpage altogether and just list everything, however long the list is (really, how long could it get and why would it be a bother?). The patch below should fix it. (It also enables a setting for listing institutions, but that's a separate issue.)

```diff
diff --git a/_config.yml b/_config.yml
index 2ab3486..992a7d2 100644
--- a/_config.yml
+++ b/_config.yml
@@ -23,13 +23,13 @@ collections:
   people:
     output: true
   person-publications:
-    output: true
+    output: false
   person-projects:
     output: true
   person-posts:
     output: true
   institutes:
-    output: false
+    output: true
 
 defaults:
   -
diff --git a/_layouts/person.html b/_layouts/person.html
index 93a1129..96bb758 100644
--- a/_layouts/person.html
+++ b/_layouts/person.html
@@ -124,12 +124,8 @@ layout: default
 {% if array.size > 0 %}
 <div class="section">
 {% include title-bar.html title="Publications" %}
-{% if array.size > site.data.settings.person-page-pubs %}
-	<div class="see-all"><a href="{{ site.baseurl }}/person-publications/{{ key }}">see all {{ array.size }} publications with {{ page.name }}</a></div>
-{% endif %}
 {% assign sorted = array | sort: "date" %}
-{% assign sorted = sorted | reverse %}
-{% for pub in sorted limit: site.data.settings.person-page-pubs %}
+{% for pub in sorted reversed %}
 	{% include publication.html pub=pub %}
 {% endfor %}
 </div>
```

**Comment by eblerjana** [comment]
I like this suggestion!

**Comment by ptrebert** [comment]
does it build correctly? if so, just apply the patch, and push an updated version of the website. We won't make this a group discussion "long list vs limited list"...

**Comment by qwx9** [comment]
Done -- could you merge your branch? It should work fine now, but please report any other glitches :)
